### ISSUE TITLE
Can your given command train the model "wikisum_model_step_500000.pt" ?

### ISSUE THREAD

**Issue by luowm7** [nlpyang/hiersumm#20]
I trained the model for 500,000 steps with the given default settings of the command line, then the model contains 15343952 parameters, and the saved .pt file is about 211MBytes. But the model wikisum_model_step_500000.pt downloaded by your link is about 395MBytes. 
Do the net parameters given in the command line differ from the model named "wikisum_model_step_500000.pt"?

**Comment by ljiiua123** [comment]
我也遇到这个问题了，然后我发现代码默认的解码器是一层，示范的命令行也没设定层数，然而下载的模型解码器是六层...

**Comment by luowm7** [comment]
> 我也遇到这个问题了，然后我发现代码默认的解码器是一层，示范的命令行也没设定层数，然而下载的模型解码器是六层...

啊这天杀的README，六层decoder就说的通了

**Comment by ljiiua123** [comment]
你好，请问一下你能够训练出论文中的结果吗，我6层解码器，训练50万步，测试rouge只有20左右，请问你知道哪里发生错误了吗...

**Comment by luowm7** [comment]
> 你好，请问一下你能够训练出论文中的结果吗，我6层解码器，训练50万步，测试rouge只有20左右，请问你知道哪里发生错误了吗...

我只训练了10万步，大概40左右的rouge-1，你测试的是哪个类型的rouge？看一下训练的参数

**Comment by bultiful** [comment]
你好啊，不知道你有没有关注：这项工作能迁移到中文数据嘛？中文数据应该如何做处理呢？ @luowm7
