### ISSUE TITLE
No such file or directory for training files

### ISSUE THREAD

**Issue by RyanOngAI** [nlpyang/hiersumm#7]
I followed the ReadMe terminal script and replace the 4 variables with the respective directory. I downloaded the ranked version of the dataset (which consists of 435 files, training, valid and test). When run the command below:

python train_abstractive.py -data_path /home/ryan/msc-project/hiersumm/src/ranked_wiki_b40 -mode train -batch_size 10500 -seed 666 -train_steps 1000000 -save_checkpoint_steps 5000  -report_every 100 -trunc_tgt_ntoken 400 -trunc_src_nblock 24 -visible_gpus 0 -gpu_ranks 0 -world_size 1 -accum_count 1 -dec_dropout 0.1 -enc_dropout 0.1 -label_smoothing 0.1 -vocab_path /home/ryan/msc-project/hiersumm/src/spm9998_3.model -model_path /home/ryan/msc-project/hiersumm/models -accum_count 1  -log_file /home/ryan/msc-project/hiersumm/log.txt  -inter_layers 6,7 -inter_heads 8 -hier

I get:

No such file or directory: '/home/ryan/msc-project/hiersumm/src/ranked_wiki_b40.train.pt'

**Comment by nlpyang** [comment]
the datapath should end with ranked_wiki_b40/wiki

**Comment by RyanOngAI** [comment]
I just chnaged the data_path to No such file or directory: '/home/ryan/msc-project/hiersumm/src/ranked_wiki_b40/wiki

and I still got the same error:

No such file or directory: '/home/ryan/msc-project/hiersumm/src/ranked_wiki_b40/wiki.train.pt'?

**Comment by nlpyang** [comment]
capitalize WIKI, this should be the prefix of your .pt filea

**Comment by RyanOngAI** [comment]
hey, I just tried it but still same type of error:

No such file or directory: '/home/ryan/msc-project/hiersumm/src/ranked_wiki_b40/WIKI.train.pt'

The directory has 413 train.pt files... see below as example:

WIKI.train.11.pt   WIKI.train.149.pt  WIKI.train.178.pt  WIKI.train.206.pt  WIKI.train.235.pt  

and it couldnt find specifically WIKI.train.pt.

Does that mean I have to concatenate all of them into one file?

Thanks!

**Comment by nlpyang** [comment]
No, the model should load multiple pt files.
Could you please run 'ls /home/ryan/msc-project/hiersumm/src/ranked_wiki_b40/' and show me the results.

**Comment by RyanOngAI** [comment]
'ls /home/ryan/msc-project/hiersumm/src/ranked_wiki_b40/' returns:

WIKI

WIKI is the folder where all the .pt files are in

**Comment by RyanOngAI** [comment]
Hi Yang,

I have fixed the problem now. Thanks for the hint! 

A quick question, how long does the model takes to train with 4 GPUs? I only have 1 GPU.

**Comment by nlpyang** [comment]
It takes 5 days on 4 gpus, so with one gpu, you will need a much longer time.
