### ISSUE TITLE
Is it trivial to apply this model to CNN/Daily Mail dataset

### ISSUE THREAD

**Issue by RyanOngAI** [nlpyang/hiersumm#8]
Hi Yang,

Thanks for sharing the code. This isn't an issue so sorry if I am not suppose to post this here. I am very new in this area but I am interested in applying this model to CNN/Daily Mail dataset for single document summarisation and was wondering if your code can easily be apply to CNN/Daily Mail dataset? Also any advice on which key file/files to change would be great!

Thank you!

Ryan

**Comment by nlpyang** [comment]
Hi,

I am not sure if CNNDM is not suitable for our model. I think you want to do is to model a document as multiple paragraphs? I would say this may be very difficult to outperform a flat model. But this is still a chance that this could bring some improvements. Only experiments can tell us.
