### ISSUE TITLE
Stuck when using multiple GPU

### ISSUE THREAD

**Issue by nlpmc** [nlpyang/hiersumm#9]
Hi~ Thanks for your code.
When I try to use four GPUs to train the model as you mentioned in the Readme, the training process stuck. I find that the original training command is `-visible_gpus 0,1,2,3 -gpu_ranks 0,1,2,4`. And when I change it to `-visible_gpus 0,1,2,3 -gpu_ranks 0,1,2,3`, this problem get fixed.

**Comment by nlpyang** [comment]
Thanks, the readme has been fixed.
